//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESolutions.Shopper.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;01505076177381&quot;;&quot;NP&quot;;&quot;Düx Industries, Op den Hoogen 30, DE-21037 Hamburg&quot;;&quot;0,000&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;20175272335&quot;;&quot;Lager&quot;;&quot;&quot;;&quot;EMAIL=1&quot;
        ///&quot;01505076177381&quot;;&quot;NP&quot;;&quot;Düx Industries, Op den Hoogen 30, DE-21037 Hamburg&quot;;&quot;0,000&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;20175272335&quot;;&quot;Lager&quot;;&quot;&quot;;&quot;EMAIL=1&quot;
        ///&quot;01505076177381&quot;;&quot;NP&quot;;&quot;Düx Industries, Op den Hoogen 30, DE-21037 Hamburg&quot;;&quot;0,000&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;20175272335&quot;;&quot;Lager&quot;;&quot;&quot;;&quot;EMAIL=1&quot;
        ///&quot;01505076177381&quot;;&quot;NP&quot;;&quot;Düx Industries, Op den Hoogen 30, DE-21037 Hamburg&quot;;&quot;0,000&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;&quot;;&quot;20175272335&quot;;&quot;Lager&quot;;&quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DpdLieferungen {
            get {
                return ResourceManager.GetString("DpdLieferungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paketnummer;Datum;Produkt - Service;Gewicht;Referenznr. 1;Referenznr. 2;Referenznr3.:;Referenznr4.:;ID Sendung;ID Versender Scan;Versanddatum;Zustelldatum;Firma (Empfänger);Name;Zu Händen;Adresse 1;Adresse 2;Land;Region;PLZ;Stadt;Tel.;Email;Ref. (Adresse);Anrede;Fax;Bemerkung (Adresse);Firma (Absender);Name;Adresse 1 (Strasse);Adresse 2;Land;Region;PLZ;Stadt;Tel.;Email;Ref. (Adresse);Anrede;Fax;COD Verwendungszweck;COD Betrag;COD Währung;COD Inkasoart;AI Länge (cm);AI Breite (cm);AI Höhe (cm);AI enthält Beg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DpdVersand {
            get {
                return ResourceManager.GetString("DpdVersand", resourceCulture);
            }
        }
    }
}
