//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Web.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESolutions.Shopper.Web.UI.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        internal static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import idle!.
        /// </summary>
        internal static string ImportIdle {
            get {
                return ResourceManager.GetString("ImportIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import running.....
        /// </summary>
        internal static string ImportRunning {
            get {
                return ResourceManager.GetString("ImportRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark for next sync.
        /// </summary>
        internal static string MarkForSync {
            get {
                return ResourceManager.GetString("MarkForSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSent.
        /// </summary>
        internal static string NotSent {
            get {
                return ResourceManager.GetString("NotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate.
        /// </summary>
        internal static string Reactivate {
            get {
                return ResourceManager.GetString("Reactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal (gross).
        /// </summary>
        internal static string SubtotalGross {
            get {
                return ResourceManager.GetString("SubtotalGross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal (net).
        /// </summary>
        internal static string SubtotalNet {
            get {
                return ResourceManager.GetString("SubtotalNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (gross).
        /// </summary>
        internal static string TotalGross {
            get {
                return ResourceManager.GetString("TotalGross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (net).
        /// </summary>
        internal static string TotalNet {
            get {
                return ResourceManager.GetString("TotalNet", resourceCulture);
            }
        }
    }
}
