//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleQA
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
