//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GermanPostcode
    {
        public System.Guid Guid { get; set; }
        public string City { get; set; }
        public string Addition { get; set; }
        public string Postcode { get; set; }
    }
}
