//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Sales = new HashSet<Sale>();
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int Id { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceStreet2 { get; set; }
        public string InvoiceStreet1 { get; set; }
        public string InvoiceCountry { get; set; }
        public string InvoicePostcode { get; set; }
        public string InvoiceCity { get; set; }
        public string InvoicePhone { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool Printed { get; set; }
        public decimal MailingCosts { get; set; }
        public decimal MailingCostsTaxRate { get; set; }
        public string UstIdNr { get; set; }
        public string EmailAddress { get; set; }
        public bool HideNetPrices { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
