//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public decimal Amount { get; set; }
        public string ArticleNumber { get; set; }
        public string ArticleName { get; set; }
        public decimal TaxRate { get; set; }
        public decimal SinglePriceGross { get; set; }
        public string StockNumber { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
