//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingCostCountry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string IsoCode2 { get; set; }
        public decimal DpdCostsUnto4kg { get; set; }
        public decimal DpdCostsUnto31_5kg { get; set; }
        public bool HideNetPrices { get; set; }
        public DhlZones DhlProductCode { get; set; }
        public decimal DhlCosts { get; set; }
        public string IsoCode3 { get; set; }
    }
}
