//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mailing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mailing()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string RecepientName { get; set; }
        public string RecepientStreet2 { get; set; }
        public string RecepientStreet1 { get; set; }
        public string RecepientCountry { get; set; }
        public string RecepientPostcode { get; set; }
        public string RecepientCity { get; set; }
        public string RecepientPhone { get; set; }
        public decimal MailingCostsSender { get; set; }
        public decimal MailingCostsRecepient { get; set; }
        public ShippingMethods ShippingMethod { get; set; }
        public string RecepientEbayName { get; set; }
        public string RecepientEmail { get; set; }
        public bool MustSyncTrackingNumber { get; set; }
        public Nullable<System.DateTime> DateOfShipping { get; set; }
        public string TrackingNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
