//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDataContext : DbContext
    {
        public MyDataContext()
            : base("name=MyDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleQA> ArticleQAs { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<GermanPostcode> GermanPostcodes { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<MailingCostsDpd> MailingCostsDpds { get; set; }
        public virtual DbSet<MaterialGroup> MaterialGroups { get; set; }
        public virtual DbSet<NumberGenerator> NumberGenerators { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<SaleItem> SaleItems { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<StockMovement> StockMovements { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<SyncerLog> SyncerLogs { get; set; }
        public virtual DbSet<Mailing> Mailings { get; set; }
        public virtual DbSet<PossibleEAN> PossibleEANs { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<ArticleVehicleAssignment> ArticleVehicleAssignments { get; set; }
        public virtual DbSet<ArticleSearch> ArticleSearches { get; set; }
        public virtual DbSet<MailingCostCountry> MailingCostCountries { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }
}
