//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleEAN
    {
        public System.Guid Guid { get; set; }
        public string EAN { get; set; }
        public Nullable<int> ArticleId { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
