//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MailingId { get; set; }
        public SaleSources Source { get; set; }
        public string EbayName { get; set; }
        public string InvoiceName { get; set; }
        public string PhoneNumber { get; set; }
        public string EMailAddress { get; set; }
        public string InvoiceStreet1 { get; set; }
        public string InvoiceStreet2 { get; set; }
        public string InvoiceCity { get; set; }
        public string InvoiceRegion { get; set; }
        public string InvoicePostcode { get; set; }
        public string InvoiceCountry { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public decimal ShippingPrice { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public string Notes { get; set; }
        public string ShippingName { get; set; }
        public string ShippingStreet1 { get; set; }
        public string ShippingStreet2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingRegion { get; set; }
        public string ShippingPostcode { get; set; }
        public string ShippingCountry { get; set; }
        public string NameOfBuyer { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public bool IsCashSale { get; set; }
        public bool ManuallyChanged { get; set; }
        public string SourceId { get; set; }
        public bool PaidWithPayPal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItem> SaleItems { get; set; }
        public virtual Mailing Mailing { get; set; }
    }
}
