//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int Id { get; set; }
        public int SaleId { get; set; }
        public int EbaySalesRecordNumber { get; set; }
        public string ExternalArticleName { get; set; }
        public string ExternalArticleNumber { get; set; }
        public string InternalArticleNumber { get; set; }
        public decimal Amount { get; set; }
        public decimal SinglePriceGross { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public decimal TaxRate { get; set; }
        public string EbayOrderLineItemID { get; set; }
        public Nullable<int> ArticleId { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual Article Article { get; set; }
    }
}
