//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Shopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.ArticleVehicleAssignments = new HashSet<ArticleVehicleAssignment>();
        }
    
        public System.Guid Guid { get; set; }
        public string Series { get; set; }
        public string ModelName { get; set; }
        public string ModelNumber { get; set; }
        public int BuiltFrom { get; set; }
        public int BuiltUntil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleVehicleAssignment> ArticleVehicleAssignments { get; set; }
    }
}
